spring:
  application:
    name: mentoria-backend
  datasource:
    url: jdbc:h2:mem:person
    username: sa
    password: admin
  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console